apiVersion: v1
kind: ConfigMap
metadata:
  name: inventory-config
  namespace: inventory-manager
data:
  POSTGRES_DB: inventory-manager-db
  POSTGRES_USER: postgres
  POSTGRES_HOST: postgres-service
  POSTGRES_PORT: "5432"
  PORT: "3001"
  NODE_ENV: production
  BASE_URL: http://localhost:30081
  NEXT_PUBLIC_API_BASE_URL: http://backend-service:3001
